# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildAndTestBicep:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Bicep Build
        # You may pin to the exact commit or the version.
        # uses: aliencube/bicep-build-actions@9f46db3c20a0bcb92b48bd300207284d164ca3db
        uses: aliencube/bicep-build-actions@v0.3
        with:
          # List of .bicep files to build, delimited by a space. eg) file1 file2 file3 ...
          files: '**/*.bicep'
          # Version of the bicep CLI. It can be the exact version (eg. `v0.3.255`), wildcard (eg. `v0.3.x`) or `latest`. If omitted, `latest` is set as default.
          
         
      - name: Run ARM TTK
        uses: aliencube/arm-ttk-actions@v0.3
        id: armtest
        with:
          path: ./Bicep
      
      - name: Show ARM TTK test result
        shell: bash
        continue-on-error: true
        run: |
          echo 'Results: ${{ toJSON(fromJSON(steps.armtest.outputs.results)) }}'
  
  validateNamingConvention:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main  
    
      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
        
    - name: Checkout naming-convention-tool repo
      uses: actions/checkout@v2
      with:
        repository: kirtregiste/BicepNamingValidationTool
        token: ${{ secrets.NAMINGVALIDATION_PAT }}
        path: naming-validation-tool
        
    - name: Display root Directory
      uses: Azure/powershell@v1
      with:
        inlineScript: |
          dir
        azPSVersion: "latest"    
        
    - name: Display naming tool Directory
      uses: Azure/powershell@v1
      with:
        inlineScript: |
          dir ./naming-validation-tool
        azPSVersion: "latest" 
    
        
      #Validate Naming Convention
    - name: Validate Naming Convention
      uses: Azure/powershell@v1
      with:
        # Specify the Az PowerShell script here.
        inlineScript: |
          ./naming-validation-tool/namingvalidation.ps1 `
          -templateFile ./Bicep/azuredeploy.bicep `
          -scope 'subscription' `
          -location eastus
        # Azure PS version to be used to execute the script, example: 1.8.0, 2.8.0, 3.4.0. To use the latest version, specify "latest".
        azPSVersion: "latest"  
        
  DeployToAzure:
    needs: 
    - validateNamingConvention
    - buildAndTestBicep    
    runs-on: ubuntu-latest
    steps:
      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        scope: subscription
        region: eastus
        #resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./Bicep/azuredeploy.bicep
        failOnStdErr: false
    
    
